name: weather
description: Weather App In Flutter
publish_to: 'none'


version: 2.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  location: ^4.2.0
  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  http: ^0.13.4
  google_fonts: ^3.0.1
  intl: ^0.17.0
  weather_icons: ^3.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1


flutter:
  fonts:
     - family: CustomIcons
       fonts:
        - asset: fonts/CustomIcons.ttf


  uses-material-design: true




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/sunny.png"
